language: php

build:
  image: default-bionic
  environment:
    php:
      - 8.2

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mongodb
  - memcached
  - redis-server

before_script:
  - composer self-update
  - composer install --prefer-dist -n

before_install:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - ./vendor/bin/phpunit tests/ --coverage-clover clover.xml
  - ./vendor/bin/phpcs --extensions=php --standard=PSR12 --ignore=*/_files/* src/ tests/
  - ./vendor/bin/phpmd ./src text ./phpmd.xml --suffixes php

after_success:
  - travis_retry php vendor/bin/coveralls -v -x clover.xml
  - bash <(curl -s https://codecov.io/bash)
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
